---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: bento/centos-7.2
    driver:
      network:
        - ['private_network', {ip: '192.168.247.21'}]
  - name: bento/debian-8.2
    driver:
      network:
        - ['private_network', {ip: '192.168.247.22'}]
  - name: bento/ubuntu-14.04
    driver:
      network:
        - ['private_network', {ip: '192.168.247.23'}]

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
      ceph:
        version: 'infernalis'
